apiVersion : apps/v1
kind: Deployment
metadata:
  name: "coolapi-deployment"
  namespace: coolapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "coolapi"
  template:
    metadata:
      labels:
        app: "coolapi"
    spec:
      containers:
        - name: "coolapi"
          image: "acrstan2022fbu.azurecr.io/coolapi:1.0.0"
          ports:
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
